### ISSUE TITLE
Vertex AI permission error: 'aiplatform.endpoints.predict'

### ISSUE THREAD

**Issue by minefire59** [rpurinton/gemini-php#4]
Hi,

I am facing the following issue:

Error Code: 403,
Message: Permission 'aiplatform.endpoints.predict' denied on resource '//aiplatform.googleapis.com/projects/help-my-setup/locations/us-east4/publishers/google/models/gemini-pro' (or it may not exist).,
Status: PERMISSION_DENIED

However, I do have the necessary permissions "aiplatform.endpoints.predict".

I am a beginner and I have tried everything I could to solve the problem, but nothing works.

Do you have any advice?

Thanks

**Comment by rpurinton** [comment]
> Hi,
> 
> I am facing the following issue:
> 
> Error Code: 403, Message: Permission 'aiplatform.endpoints.predict' denied on resource '//aiplatform.googleapis.com/projects/help-my-setup/locations/us-east4/publishers/google/models/gemini-pro' (or it may not exist)., Status: PERMISSION_DENIED
> 
> However, I do have the necessary permissions "aiplatform.endpoints.predict".
> 
> I am a beginner and I have tried everything I could to solve the problem, but nothing works.
> 
> Do you have any advice?
> 
> Thanks

Please see https://github.com/rpurinton/gemini-php/issues/2
